name: CustomItemsLib
main: metadev.digital.metacustomitemslib.Core
version: 2.1.0
description: CustomItemsLib is shared library used by BagOfGold and MobHunting.
dev-url: https://github.com/Metadev-Digital/CustomItemsLib
author: JebusChrystler
depend: []
loadbefore:
  - BagOfGold
  - MobHunting
softdepend:
  - Reserve
  - Vault
  - PerWorldInventory
  - Citizens
  - Essentials
  - ProtocolLib
  - PacketListenerApi
  - ItemFrameShops
  - Multiverse-Core
  - TitleManager
  - CMI
  - CMILib
  - BossBarAPI
  - BarAPI
  - ActionBar
  - TitleAPI
  - TitleManager
  - ActionBarAPI
  - ActionAnnouncer
api-version: 1.21
commands:
  customitemslib:
    description: Allows you to use commands in CustomItemsLib
    permission: customitemslib.cmd
    aliases:
      - cil
    usage: /<command> command
permissions:
  customitemslib.cmd:
    description: Allows a player to use the customitemslib command
    default: true
  customitemslib.update:
    description: Allows a player to check SpigotMc for updates to the plugin
    default: op
    children:
      customitemslib.cmd: true
  customitemslib.reload:
    description: Allows you to reload the configuration
    default: op
    children:
      customitemslib.cmd: true
  customitemslib.version:
    description: Allows you to get plugin version.
    default: true
    children:
      customitemslib.cmd: true
  customitemslib.debug:
    description: Allows you to enable/disable debugmode and see debug information in the server console.
    default: op
    children:
      customitemslib.cmd: true